repos:

- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    language: system

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
  - id: mypy
    exclude: '^(docs/)|(examples/)'

- repo: local
  hooks:

  - id: prospector
    name: prospector
    entry: prospector
    types: [file, python]
    language: system
    exclude: '^(docs/)|(examples/)'
