# -*- coding: utf-8 -*-
"""Basic PorousMaterials input generator."""
from __future__ import absolute_import
import os
from string import Template
from copy import deepcopy


class PorousMaterialsInput:
    """
    PorousMaterials Input generator.
    It takes parameters as the dictionary and
    also reads the template, and then generates
    necessary variables and then replace them in the Template
    and creates the input for the calculation.
    """

    def __init__(self, params):
        self.params = deepcopy(params)

    def render(self):
        """
        Performing the described tasks.
        """

        output = "### Generated by AiiDA ###"
        output += ""
        params = deepcopy(self.params)
        # print(params)
        # tmp = "/storage/brno9-ceitec/home/pezhman/projects/git_repos/aiida-porousmaterials/aiida_porousmaterials/templates/ev_only_lj_template.jl"
        # tmp = os.path.join(os.path.abspath('./templates'), self.params['input_template'])

        dir = os.path.dirname(os.path.abspath(__file__))
        tmppath = '{}/templates/{}.jl'.format(dir, self.params['input_template'])

        with open(tmppath) as template:
            lines = template.read()

        inp = Template(lines).substitute(params)
        output += inp
        # print(inp)
        # with open('framework.jl','w') as inputfile:
            # inputfile.write(str(inp))

        return output
