# -*- coding: utf-8 -*-
from string import Template
from copy import deepcopy


class PorousMaterialsInput(object):
    """
    PorousMaterials Input generator.
    It takes parameters as the dictionary and
    also reads the template, and then generates
    necessary variables and then replace them in the Template
    and creates the input for the calculation.
    """

    def __init__(self, params):
        self.params = deepcopy(params)

    def render(self):
        """
        Performing the described tasks.
        """

        output = ["!!! Generated by AiiDA !!!"]
        params = deepcopy(self.params)
        
